### ISSUE TITLE
AssertLinkExists fails with whitespace

### ISSUE THREAD

**Issue by jaysson** [ssddanbrown/asserthtml#1]
If the HTML looks like
```html
<a href="https://google.com">
    Go to google
</a>
```
The following assertion fails.
```php
$html->assertLinkExists("https://google.com", "Go to google");
```
I am now using this instead, which works.
```php
$html->assertElementContains("a[href='https://google.com']", "Go to google");
```

**Comment by ssddanbrown** [comment]
Thanks for reporting, but this is expected behaviour. The method call is not a `contains` method, so the text match is an exact match. The inclusion of white-space can often be important, especially for an inline element such as an anchor tag.
